# Generated by Django 3.1.5 on 2021-01-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pickuppoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(help_text='Enter the adress of the pickup point', max_length=200)),
                ('discription', models.CharField(help_text='Enter a discription of the point', max_length=200)),
                ('city', models.CharField(blank=True, choices=[('1', 'Hillsborough'), ('2', 'Durham')], default='1', max_length=1)),
                ('street', models.CharField(blank=True, choices=[('1', 'East'), ('2', 'West'), ('3', 'King'), ('4', 'Queen')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='wastecenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the center', max_length=200)),
                ('summery', models.CharField(help_text='A brief discription', max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('adress', models.CharField(blank=True, choices=[('1', 'batteries'), ('2', 'oil'), ('3', 'acids'), ('4', 'all three')], default='4', max_length=1)),
            ],
        ),
    ]
