# Generated by Django 3.1.5 on 2021-01-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volinteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Enter your first name (e.g. Jhon)', max_length=200)),
                ('lastname', models.CharField(help_text='Enter your last name (e.g. Jhon)', max_length=200)),
                ('username', models.CharField(help_text='Enter your username (e.g. Jhon)', max_length=200)),
                ('adress', models.CharField(blank=True, choices=[('10', 'The moon'), ('11', '323 East West st, Hilsborough, 27278'), ('12', '576 North South st, Hillsborough, 27278'), ('13', '1536 King st, Hillsborough, 27278'), ('14', '12021 President st, Hillsborough, 27278'), ('21', '321 Book st, Durham, 27517'), ('22', '456 Novel st, Durham, 27517'), ('23', '613 Film st, Durham, 27517'), ('24', '11 TV st, Durham, 27517')], default='10', help_text='Your adress', max_length=2)),
            ],
        ),
    ]
