# Generated by Django 3.1.5 on 2021-01-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wastecenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the center', max_length=200)),
                ('adress', models.CharField(help_text='Enter the adress of the center', max_length=200)),
                ('summery', models.CharField(help_text='A brief discription', max_length=200)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='volinteer',
            name='username',
            field=models.CharField(help_text='Enter your username (e.g. Jhon123)', max_length=200),
        ),
    ]
