# Generated by Django 3.1.5 on 2021-01-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20210124_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wastecenter',
        ),
    ]
